trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Use '8.x' instead of 'net8.0' for .NET Core 8

- task: DotNetCoreCLI@2
  displayName: 'Build Backend'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Use '17.x' for React 17
    checkLatest: true

- script: |
    cd src/Web/ClientApp
    npm install
    npm run build
  displayName: 'Build Frontend'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\src\Web\ClientApp\build'  # Adjusted path
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/react-app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/react-app'
    ArtifactName: 'react-app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'backend'
